services:
  web:
    # image: maricm123/heartapp:latest
    image: 458845363232.dkr.ecr.eu-north-1.amazonaws.com/heartapp:latest
#    command: >
#      gunicorn django_heart.asgi:application
#      -k uvicorn.workers.UvicornWorker
#      --bind 0.0.0.0:8000
#      --workers 2
#      --timeout 0
#      --graceful-timeout 0
#      --keep-alive 120
    command: >
      uvicorn django_heart.asgi:application
      --host 0.0.0.0
      --port 8000
      --workers 2
      --ws-ping-interval 20
      --ws-ping-timeout 30
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    restart: always

  db:
    image: postgres:15
    env_file:
      - .env.prod.db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    restart: always

volumes:
  postgres_data:
