services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: >
      gunicorn django_heart.asgi:application
      -k uvicorn.workers.UvicornWorker
      --bind 0.0.0.0:8000
      --workers 4
      --timeout 0
      --graceful-timeout 0
      --keep-alive 120
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.docker
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DJ_DB_USER}
      - POSTGRES_PASSWORD=${DJ_DB_PASSWORD}
      - POSTGRES_DB=${DJ_DB_NAME}
  redis:
    image: redis:7
    ports:
      - "6380:6379"  # 6380 je za lokalni pristup ako ti treba

volumes:
  postgres_data:
